name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 15.x
        uses: actions/setup-node@master
        with:
          node-version: 15.x

      - name: Install Dependencies
        uses: bahmutov/npm-install@HEAD
        with:
          install-command: yarn --frozen-lockfile --silent
        run: npm t

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@640c4a5d646991720131ef3b6e0e63220de5dddf
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
